name: Build & Release

on:
  push:
    branches: [ "main" ]
    tags:
      - '*'
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:

  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        go: [1.19.x]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go }}

    - run: echo "GOOS=$(go env GOOS)" >> $GITHUB_ENV

    - name: Build for ${{ matrix.os }}
      run: |
        go build -o go_pay_taxes -v ./...
        zip go_pay_taxes-${{ env.GOOS }}.zip go_pay_taxes

    - name: Archive and upload artifacts
      uses: actions/upload-artifact@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        if-no-files-found: error
        path: go_pay_taxes-${{ env.GOOS }}.zip

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:

    - name: Download artifacts
      uses: actions/download-artifact@v3

    - run: find .

    - name: Publish
      uses: softprops/action-gh-release@v1
      with:
        name: release-${{ github.ref_name }}
        fail_on_unmatched_files: true
        draft: false
        generate_release_notes: true
        files: |
          artifact/*
